// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.1
// source: protocol.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义协议包装体
type PBNetMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proto   string `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`      //发送消息协议的名字
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`  //协议里具体对应消息的结构，对应的协议名字的结构
	Session int32  `protobuf:"varint,3,opt,name=session,proto3" json:"session,omitempty"` //RPC调用时的唯一ID
}

func (x *PBNetMsg) Reset() {
	*x = PBNetMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBNetMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBNetMsg) ProtoMessage() {}

func (x *PBNetMsg) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBNetMsg.ProtoReflect.Descriptor instead.
func (*PBNetMsg) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *PBNetMsg) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *PBNetMsg) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PBNetMsg) GetSession() int32 {
	if x != nil {
		return x.Session
	}
	return 0
}

type PBLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *PBLoginReq) Reset() {
	*x = PBLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBLoginReq) ProtoMessage() {}

func (x *PBLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBLoginReq.ProtoReflect.Descriptor instead.
func (*PBLoginReq) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *PBLoginReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *PBLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PBLoginRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     int64     `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name    string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SceneId int32     `protobuf:"varint,3,opt,name=sceneId,proto3" json:"sceneId,omitempty"`
	Items   []*PBItem `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	Money   int64     `protobuf:"varint,5,opt,name=money,proto3" json:"money,omitempty"`
}

func (x *PBLoginRsp) Reset() {
	*x = PBLoginRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBLoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBLoginRsp) ProtoMessage() {}

func (x *PBLoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBLoginRsp.ProtoReflect.Descriptor instead.
func (*PBLoginRsp) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *PBLoginRsp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PBLoginRsp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PBLoginRsp) GetSceneId() int32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *PBLoginRsp) GetItems() []*PBItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PBLoginRsp) GetMoney() int64 {
	if x != nil {
		return x.Money
	}
	return 0
}

type PBEnterSceneReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PBEnterSceneReq) Reset() {
	*x = PBEnterSceneReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBEnterSceneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBEnterSceneReq) ProtoMessage() {}

func (x *PBEnterSceneReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBEnterSceneReq.ProtoReflect.Descriptor instead.
func (*PBEnterSceneReq) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{3}
}

type SceneObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjId     int32   `protobuf:"varint,1,opt,name=objId,proto3" json:"objId,omitempty"`
	Type      int32   `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Hp        int32   `protobuf:"varint,3,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp     int32   `protobuf:"varint,4,opt,name=maxHp,proto3" json:"maxHp,omitempty"`
	Mp        int32   `protobuf:"varint,5,opt,name=mp,proto3" json:"mp,omitempty"`
	MaxMp     int32   `protobuf:"varint,6,opt,name=maxMp,proto3" json:"maxMp,omitempty"`
	PositionX float32 `protobuf:"fixed32,7,opt,name=positionX,proto3" json:"positionX,omitempty"`
	PositionY float32 `protobuf:"fixed32,8,opt,name=positionY,proto3" json:"positionY,omitempty"`
	PositionZ float32 `protobuf:"fixed32,9,opt,name=positionZ,proto3" json:"positionZ,omitempty"`
	Level     int32   `protobuf:"varint,10,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *SceneObject) Reset() {
	*x = SceneObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneObject) ProtoMessage() {}

func (x *SceneObject) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneObject.ProtoReflect.Descriptor instead.
func (*SceneObject) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *SceneObject) GetObjId() int32 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

func (x *SceneObject) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *SceneObject) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *SceneObject) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *SceneObject) GetMp() int32 {
	if x != nil {
		return x.Mp
	}
	return 0
}

func (x *SceneObject) GetMaxMp() int32 {
	if x != nil {
		return x.MaxMp
	}
	return 0
}

func (x *SceneObject) GetPositionX() float32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *SceneObject) GetPositionY() float32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *SceneObject) GetPositionZ() float32 {
	if x != nil {
		return x.PositionZ
	}
	return 0
}

func (x *SceneObject) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type PBEnterSceneRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SceneObjects []*SceneObject `protobuf:"bytes,1,rep,name=sceneObjects,proto3" json:"sceneObjects,omitempty"`
	Self         *SceneObject   `protobuf:"bytes,2,opt,name=self,proto3" json:"self,omitempty"`
}

func (x *PBEnterSceneRsp) Reset() {
	*x = PBEnterSceneRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBEnterSceneRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBEnterSceneRsp) ProtoMessage() {}

func (x *PBEnterSceneRsp) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBEnterSceneRsp.ProtoReflect.Descriptor instead.
func (*PBEnterSceneRsp) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *PBEnterSceneRsp) GetSceneObjects() []*SceneObject {
	if x != nil {
		return x.SceneObjects
	}
	return nil
}

func (x *PBEnterSceneRsp) GetSelf() *SceneObject {
	if x != nil {
		return x.Self
	}
	return nil
}

type PBEnterSceneNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object *SceneObject `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
}

func (x *PBEnterSceneNotify) Reset() {
	*x = PBEnterSceneNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBEnterSceneNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBEnterSceneNotify) ProtoMessage() {}

func (x *PBEnterSceneNotify) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBEnterSceneNotify.ProtoReflect.Descriptor instead.
func (*PBEnterSceneNotify) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *PBEnterSceneNotify) GetObject() *SceneObject {
	if x != nil {
		return x.Object
	}
	return nil
}

type PBAttackReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjId int32 `protobuf:"varint,1,opt,name=objId,proto3" json:"objId,omitempty"`
}

func (x *PBAttackReq) Reset() {
	*x = PBAttackReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBAttackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBAttackReq) ProtoMessage() {}

func (x *PBAttackReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBAttackReq.ProtoReflect.Descriptor instead.
func (*PBAttackReq) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *PBAttackReq) GetObjId() int32 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

type PBAttackRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttackObjId   int32 `protobuf:"varint,1,opt,name=AttackObjId,proto3" json:"AttackObjId,omitempty"`
	AttackedObjId int32 `protobuf:"varint,2,opt,name=AttackedObjId,proto3" json:"AttackedObjId,omitempty"`
	Damage        int32 `protobuf:"varint,3,opt,name=damage,proto3" json:"damage,omitempty"`
}

func (x *PBAttackRsp) Reset() {
	*x = PBAttackRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBAttackRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBAttackRsp) ProtoMessage() {}

func (x *PBAttackRsp) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBAttackRsp.ProtoReflect.Descriptor instead.
func (*PBAttackRsp) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *PBAttackRsp) GetAttackObjId() int32 {
	if x != nil {
		return x.AttackObjId
	}
	return 0
}

func (x *PBAttackRsp) GetAttackedObjId() int32 {
	if x != nil {
		return x.AttackedObjId
	}
	return 0
}

func (x *PBAttackRsp) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

type PBAttackNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttackObjId   int32 `protobuf:"varint,1,opt,name=AttackObjId,proto3" json:"AttackObjId,omitempty"`
	AttackedObjId int32 `protobuf:"varint,2,opt,name=AttackedObjId,proto3" json:"AttackedObjId,omitempty"`
	Damage        int32 `protobuf:"varint,3,opt,name=damage,proto3" json:"damage,omitempty"`
}

func (x *PBAttackNotify) Reset() {
	*x = PBAttackNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBAttackNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBAttackNotify) ProtoMessage() {}

func (x *PBAttackNotify) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBAttackNotify.ProtoReflect.Descriptor instead.
func (*PBAttackNotify) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *PBAttackNotify) GetAttackObjId() int32 {
	if x != nil {
		return x.AttackObjId
	}
	return 0
}

func (x *PBAttackNotify) GetAttackedObjId() int32 {
	if x != nil {
		return x.AttackedObjId
	}
	return 0
}

func (x *PBAttackNotify) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

type PBObjectDieNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjId int32 `protobuf:"varint,1,opt,name=objId,proto3" json:"objId,omitempty"`
}

func (x *PBObjectDieNotify) Reset() {
	*x = PBObjectDieNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBObjectDieNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBObjectDieNotify) ProtoMessage() {}

func (x *PBObjectDieNotify) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBObjectDieNotify.ProtoReflect.Descriptor instead.
func (*PBObjectDieNotify) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *PBObjectDieNotify) GetObjId() int32 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

type PBUpdateResourceNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exp   int64     `protobuf:"varint,1,opt,name=exp,proto3" json:"exp,omitempty"`
	Level int32     `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Money int64     `protobuf:"varint,3,opt,name=money,proto3" json:"money,omitempty"`
	Items []*PBItem `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *PBUpdateResourceNotify) Reset() {
	*x = PBUpdateResourceNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBUpdateResourceNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBUpdateResourceNotify) ProtoMessage() {}

func (x *PBUpdateResourceNotify) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBUpdateResourceNotify.ProtoReflect.Descriptor instead.
func (*PBUpdateResourceNotify) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *PBUpdateResourceNotify) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PBUpdateResourceNotify) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PBUpdateResourceNotify) GetMoney() int64 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *PBUpdateResourceNotify) GetItems() []*PBItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PBMoveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PositionX float32 `protobuf:"fixed32,1,opt,name=positionX,proto3" json:"positionX,omitempty"`
	PositionY float32 `protobuf:"fixed32,2,opt,name=positionY,proto3" json:"positionY,omitempty"`
	PositionZ float32 `protobuf:"fixed32,3,opt,name=positionZ,proto3" json:"positionZ,omitempty"`
	Speed     float32 `protobuf:"fixed32,4,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *PBMoveReq) Reset() {
	*x = PBMoveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBMoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBMoveReq) ProtoMessage() {}

func (x *PBMoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBMoveReq.ProtoReflect.Descriptor instead.
func (*PBMoveReq) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *PBMoveReq) GetPositionX() float32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *PBMoveReq) GetPositionY() float32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *PBMoveReq) GetPositionZ() float32 {
	if x != nil {
		return x.PositionZ
	}
	return 0
}

func (x *PBMoveReq) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type PBMoveNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjId     int32   `protobuf:"varint,1,opt,name=objId,proto3" json:"objId,omitempty"`
	PositionX float32 `protobuf:"fixed32,2,opt,name=positionX,proto3" json:"positionX,omitempty"`
	PositionY float32 `protobuf:"fixed32,3,opt,name=positionY,proto3" json:"positionY,omitempty"`
	PositionZ float32 `protobuf:"fixed32,4,opt,name=positionZ,proto3" json:"positionZ,omitempty"`
	Speed     float32 `protobuf:"fixed32,5,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *PBMoveNotify) Reset() {
	*x = PBMoveNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBMoveNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBMoveNotify) ProtoMessage() {}

func (x *PBMoveNotify) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBMoveNotify.ProtoReflect.Descriptor instead.
func (*PBMoveNotify) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{13}
}

func (x *PBMoveNotify) GetObjId() int32 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

func (x *PBMoveNotify) GetPositionX() float32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *PBMoveNotify) GetPositionY() float32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *PBMoveNotify) GetPositionZ() float32 {
	if x != nil {
		return x.PositionZ
	}
	return 0
}

func (x *PBMoveNotify) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type PBSyncPositionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PositionX float32 `protobuf:"fixed32,1,opt,name=positionX,proto3" json:"positionX,omitempty"`
	PositionY float32 `protobuf:"fixed32,2,opt,name=positionY,proto3" json:"positionY,omitempty"`
	PositionZ float32 `protobuf:"fixed32,3,opt,name=positionZ,proto3" json:"positionZ,omitempty"`
}

func (x *PBSyncPositionReq) Reset() {
	*x = PBSyncPositionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBSyncPositionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBSyncPositionReq) ProtoMessage() {}

func (x *PBSyncPositionReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBSyncPositionReq.ProtoReflect.Descriptor instead.
func (*PBSyncPositionReq) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{14}
}

func (x *PBSyncPositionReq) GetPositionX() float32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *PBSyncPositionReq) GetPositionY() float32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *PBSyncPositionReq) GetPositionZ() float32 {
	if x != nil {
		return x.PositionZ
	}
	return 0
}

type PBItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId int32 `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Count  int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *PBItem) Reset() {
	*x = PBItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBItem) ProtoMessage() {}

func (x *PBItem) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBItem.ProtoReflect.Descriptor instead.
func (*PBItem) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{15}
}

func (x *PBItem) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *PBItem) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PBUseItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId int32 `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Count  int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *PBUseItemReq) Reset() {
	*x = PBUseItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBUseItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBUseItemReq) ProtoMessage() {}

func (x *PBUseItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBUseItemReq.ProtoReflect.Descriptor instead.
func (*PBUseItemReq) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{16}
}

func (x *PBUseItemReq) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *PBUseItemReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PBUseItemRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*PBItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *PBUseItemRsp) Reset() {
	*x = PBUseItemRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBUseItemRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBUseItemRsp) ProtoMessage() {}

func (x *PBUseItemRsp) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBUseItemRsp.ProtoReflect.Descriptor instead.
func (*PBUseItemRsp) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{17}
}

func (x *PBUseItemRsp) GetItems() []*PBItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_protocol_proto protoreflect.FileDescriptor

var file_protocol_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x54, 0x0a, 0x08, 0x50, 0x42, 0x4e, 0x65, 0x74, 0x4d, 0x73, 0x67,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x42, 0x0a, 0x0a, 0x50, 0x42,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x84,
	0x01, 0x0a, 0x0a, 0x50, 0x42, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x20, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x42, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x50, 0x42, 0x45, 0x6e, 0x74, 0x65, 0x72,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x22, 0xf3, 0x01, 0x0a, 0x0b, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x62, 0x6a, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x62, 0x6a, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x68, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x78, 0x48, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6d, 0x61, 0x78, 0x48, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6d, 0x70, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x78, 0x4d,
	0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x78, 0x4d, 0x70, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5a, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5a, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x6b,
	0x0a, 0x0f, 0x50, 0x42, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x73,
	0x70, 0x12, 0x33, 0x0a, 0x0c, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x0c, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x23, 0x0a, 0x04, 0x73, 0x65, 0x6c, 0x66, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x04, 0x73, 0x65, 0x6c, 0x66, 0x22, 0x3d, 0x0a, 0x12, 0x50,
	0x42, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x12, 0x27, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x23, 0x0a, 0x0b, 0x50, 0x42,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x62, 0x6a,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x62, 0x6a, 0x49, 0x64, 0x22,
	0x6d, 0x0a, 0x0b, 0x50, 0x42, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x73, 0x70, 0x12, 0x20,
	0x0a, 0x0b, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x4f, 0x62, 0x6a, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x4f, 0x62, 0x6a, 0x49, 0x64,
	0x12, 0x24, 0x0a, 0x0d, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x65,
	0x64, 0x4f, 0x62, 0x6a, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x70,
	0x0a, 0x0e, 0x50, 0x42, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x12, 0x20, 0x0a, 0x0b, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x4f, 0x62, 0x6a, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x4f, 0x62, 0x6a,
	0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x4f, 0x62,
	0x6a, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x6b, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x6d, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65,
	0x22, 0x29, 0x0a, 0x11, 0x50, 0x42, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x69, 0x65, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x62, 0x6a, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x62, 0x6a, 0x49, 0x64, 0x22, 0x78, 0x0a, 0x16, 0x50,
	0x42, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x6f,
	0x6e, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x42, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x7b, 0x0a, 0x09, 0x50, 0x42, 0x4d, 0x6f, 0x76, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5a, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5a, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65,
	0x65, 0x64, 0x22, 0x94, 0x01, 0x0a, 0x0c, 0x50, 0x42, 0x4d, 0x6f, 0x76, 0x65, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x62, 0x6a, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6f, 0x62, 0x6a, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x59, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x59, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x5a, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x5a, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x22, 0x6d, 0x0a, 0x11, 0x50, 0x42, 0x53,
	0x79, 0x6e, 0x63, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5a, 0x22, 0x36, 0x0a, 0x06, 0x50, 0x42, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x3c, 0x0a, 0x0c, 0x50, 0x42, 0x55, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x30,
	0x0a, 0x0c, 0x50, 0x42, 0x55, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x73, 0x70, 0x12, 0x20,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x70, 0x62, 0x2e, 0x50, 0x42, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protocol_proto_rawDescOnce sync.Once
	file_protocol_proto_rawDescData = file_protocol_proto_rawDesc
)

func file_protocol_proto_rawDescGZIP() []byte {
	file_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_proto_rawDescData)
	})
	return file_protocol_proto_rawDescData
}

var file_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_protocol_proto_goTypes = []interface{}{
	(*PBNetMsg)(nil),               // 0: pb.PBNetMsg
	(*PBLoginReq)(nil),             // 1: pb.PBLoginReq
	(*PBLoginRsp)(nil),             // 2: pb.PBLoginRsp
	(*PBEnterSceneReq)(nil),        // 3: pb.PBEnterSceneReq
	(*SceneObject)(nil),            // 4: pb.SceneObject
	(*PBEnterSceneRsp)(nil),        // 5: pb.PBEnterSceneRsp
	(*PBEnterSceneNotify)(nil),     // 6: pb.PBEnterSceneNotify
	(*PBAttackReq)(nil),            // 7: pb.PBAttackReq
	(*PBAttackRsp)(nil),            // 8: pb.PBAttackRsp
	(*PBAttackNotify)(nil),         // 9: pb.PBAttackNotify
	(*PBObjectDieNotify)(nil),      // 10: pb.PBObjectDieNotify
	(*PBUpdateResourceNotify)(nil), // 11: pb.PBUpdateResourceNotify
	(*PBMoveReq)(nil),              // 12: pb.PBMoveReq
	(*PBMoveNotify)(nil),           // 13: pb.PBMoveNotify
	(*PBSyncPositionReq)(nil),      // 14: pb.PBSyncPositionReq
	(*PBItem)(nil),                 // 15: pb.PBItem
	(*PBUseItemReq)(nil),           // 16: pb.PBUseItemReq
	(*PBUseItemRsp)(nil),           // 17: pb.PBUseItemRsp
}
var file_protocol_proto_depIdxs = []int32{
	15, // 0: pb.PBLoginRsp.items:type_name -> pb.PBItem
	4,  // 1: pb.PBEnterSceneRsp.sceneObjects:type_name -> pb.SceneObject
	4,  // 2: pb.PBEnterSceneRsp.self:type_name -> pb.SceneObject
	4,  // 3: pb.PBEnterSceneNotify.object:type_name -> pb.SceneObject
	15, // 4: pb.PBUpdateResourceNotify.items:type_name -> pb.PBItem
	15, // 5: pb.PBUseItemRsp.items:type_name -> pb.PBItem
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_protocol_proto_init() }
func file_protocol_proto_init() {
	if File_protocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBNetMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBLoginRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBEnterSceneReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBEnterSceneRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBEnterSceneNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBAttackReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBAttackRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBAttackNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBObjectDieNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBUpdateResourceNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBMoveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBMoveNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBSyncPositionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBUseItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBUseItemRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_proto_depIdxs,
		MessageInfos:      file_protocol_proto_msgTypes,
	}.Build()
	File_protocol_proto = out.File
	file_protocol_proto_rawDesc = nil
	file_protocol_proto_goTypes = nil
	file_protocol_proto_depIdxs = nil
}
